"""Pydantic schemas package."""

from app.schemas.common import (
    Pagination,
    PaginatedResponse,
    ErrorResponse,
    ErrorDetail,
    create_pagination,
)
from app.schemas.auth import (
    LoginRequest,
    RegisterRequest,
    TokenResponse,
    RefreshRequest,
    ApiKeyCreate,
    ApiKeyResponse,
)
from app.schemas.user import (
    UserResponse,
    UserUpdate,
    PublicUserResponse,
)
from app.schemas.book import (
    BookCategory,
    Visibility,
    BookStatus,
    BookStats,
    UserBrief,
    BookCreate,
    BookUpdate,
    BookFilters,
    BookResponse,
    BookListItem,
    BookListResponse,
    BookUploadResponse,
    DownloadUrlResponse,
)
from app.schemas.rating import (
    RatingCreate,
    RatingUpdate,
    RatingResponse,
    RatingListResponse,
    RatingSummary,
    FavoriteResponse,
    FavoriteListResponse,
)
from app.schemas.chat import (
    MessageRole,
    FinishReason,
    ChatSessionCreate,
    ChatSessionUpdate,
    ChatMessageCreate,
    MessageFeedbackCreate,
    BookBrief,
    ChatMessageResponse,
    ChatSessionResponse,
    ChatSessionDetail,
    ChatSessionListItem,
    ChatSessionListResponse,
    ChatMessageListResponse,
    MessageFeedbackResponse,
    StreamChunk,
)
from app.schemas.billing import (
    OperationType,
    CreditBalanceResponse,
    TransactionResponse,
    TransactionListResponse,
    UsageLimitsResponse,
    UsageSummaryResponse,
    CostEstimateResponse,
    CostEstimateRequest,
    TransactionFilters,
    InsufficientCreditsError,
    UsageLimitExceededError,
)

__all__ = [
    # Common
    "Pagination",
    "PaginatedResponse",
    "ErrorResponse",
    "ErrorDetail",
    "create_pagination",
    # Auth
    "LoginRequest",
    "RegisterRequest",
    "TokenResponse",
    "RefreshRequest",
    "ApiKeyCreate",
    "ApiKeyResponse",
    # User
    "UserResponse",
    "UserUpdate",
    "PublicUserResponse",
    # Book
    "BookCategory",
    "Visibility",
    "BookStatus",
    "BookStats",
    "UserBrief",
    "BookCreate",
    "BookUpdate",
    "BookFilters",
    "BookResponse",
    "BookListItem",
    "BookListResponse",
    "BookUploadResponse",
    "DownloadUrlResponse",
    # Rating
    "RatingCreate",
    "RatingUpdate",
    "RatingResponse",
    "RatingListResponse",
    "RatingSummary",
    "FavoriteResponse",
    "FavoriteListResponse",
    # Chat
    "MessageRole",
    "FinishReason",
    "ChatSessionCreate",
    "ChatSessionUpdate",
    "ChatMessageCreate",
    "MessageFeedbackCreate",
    "BookBrief",
    "ChatMessageResponse",
    "ChatSessionResponse",
    "ChatSessionDetail",
    "ChatSessionListItem",
    "ChatSessionListResponse",
    "ChatMessageListResponse",
    "MessageFeedbackResponse",
    "StreamChunk",
    # Billing
    "OperationType",
    "CreditBalanceResponse",
    "TransactionResponse",
    "TransactionListResponse",
    "UsageLimitsResponse",
    "UsageSummaryResponse",
    "CostEstimateResponse",
    "CostEstimateRequest",
    "TransactionFilters",
    "InsufficientCreditsError",
    "UsageLimitExceededError",
]
