"""Pydantic schemas package."""

from app.schemas.auth import (
    ApiKeyCreate,
    ApiKeyResponse,
    LoginRequest,
    RefreshRequest,
    RegisterRequest,
    TokenResponse,
)
from app.schemas.billing import (
    CostEstimateRequest,
    CostEstimateResponse,
    CreditBalanceResponse,
    InsufficientCreditsError,
    OperationType,
    TransactionFilters,
    TransactionListResponse,
    TransactionResponse,
    UsageLimitExceededError,
    UsageLimitsResponse,
    UsageSummaryResponse,
)
from app.schemas.book import (
    BookCategory,
    BookCreate,
    BookFilters,
    BookListItem,
    BookListResponse,
    BookResponse,
    BookStats,
    BookStatus,
    BookUpdate,
    BookUploadResponse,
    DownloadUrlResponse,
    UserBrief,
    Visibility,
)
from app.schemas.chat import (
    BookBrief,
    ChatMessageCreate,
    ChatMessageListResponse,
    ChatMessageResponse,
    ChatSessionCreate,
    ChatSessionDetail,
    ChatSessionListItem,
    ChatSessionListResponse,
    ChatSessionResponse,
    ChatSessionUpdate,
    FinishReason,
    MessageFeedbackCreate,
    MessageFeedbackResponse,
    MessageRole,
    StreamChunk,
)
from app.schemas.common import (
    ErrorDetail,
    ErrorResponse,
    PaginatedResponse,
    Pagination,
    create_pagination,
)
from app.schemas.page import (
    BookChunksResponse,
    ChunkResponse,
    GenerationStatus,
    PageCitation,
    PageDetailResponse,
    PageGenerationRequest,
    PageGenerationResponse,
    PageListResponse,
    PageMetadata,
    RAGContext,
)
from app.schemas.rating import (
    FavoriteListResponse,
    FavoriteResponse,
    RatingCreate,
    RatingListResponse,
    RatingResponse,
    RatingSummary,
    RatingUpdate,
)
from app.schemas.user import (
    PublicUserResponse,
    UserResponse,
    UserUpdate,
)

__all__ = [
    # Common
    "Pagination",
    "PaginatedResponse",
    "ErrorResponse",
    "ErrorDetail",
    "create_pagination",
    # Auth
    "LoginRequest",
    "RegisterRequest",
    "TokenResponse",
    "RefreshRequest",
    "ApiKeyCreate",
    "ApiKeyResponse",
    # User
    "UserResponse",
    "UserUpdate",
    "PublicUserResponse",
    # Book
    "BookCategory",
    "Visibility",
    "BookStatus",
    "BookStats",
    "UserBrief",
    "BookCreate",
    "BookUpdate",
    "BookFilters",
    "BookResponse",
    "BookListItem",
    "BookListResponse",
    "BookUploadResponse",
    "DownloadUrlResponse",
    # Rating
    "RatingCreate",
    "RatingUpdate",
    "RatingResponse",
    "RatingListResponse",
    "RatingSummary",
    "FavoriteResponse",
    "FavoriteListResponse",
    # Chat
    "MessageRole",
    "FinishReason",
    "ChatSessionCreate",
    "ChatSessionUpdate",
    "ChatMessageCreate",
    "MessageFeedbackCreate",
    "BookBrief",
    "ChatMessageResponse",
    "ChatSessionResponse",
    "ChatSessionDetail",
    "ChatSessionListItem",
    "ChatSessionListResponse",
    "ChatMessageListResponse",
    "MessageFeedbackResponse",
    "StreamChunk",
    # Billing
    "OperationType",
    "CreditBalanceResponse",
    "TransactionResponse",
    "TransactionListResponse",
    "UsageLimitsResponse",
    "UsageSummaryResponse",
    "CostEstimateResponse",
    "CostEstimateRequest",
    "TransactionFilters",
    "InsufficientCreditsError",
    "UsageLimitExceededError",
    # Page
    "GenerationStatus",
    "PageMetadata",
    "PageListResponse",
    "PageDetailResponse",
    "PageGenerationRequest",
    "PageGenerationResponse",
    "ChunkResponse",
    "BookChunksResponse",
    "PageCitation",
    "RAGContext",
]
